FROM wordpress:6.9.0-php8.2-apache
ARG UID
ARG GID

# Install wp-cli
RUN curl -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && \
    chmod +x /usr/local/bin/wp

# Install Composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Configure user and permissions
RUN usermod -u $UID www-data && \
    groupmod -g $GID www-data && \
    chown -R $UID:$GID /var/www/html

# Set wp-cli alias
RUN echo "alias wp='wp --allow-root'" >> /root/.bashrc

USER www-data